// <auto-generated />
using System;
using AddressLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressLibrary.Migrations
{
    [DbContext(typeof(AddressDbContext))]
    [Migration("20260320070100_poprawka_kodypocztowe")]
    partial class poprawka_kodypocztowe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressLibrary.Models.Adres", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Gmina")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Komentarz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Kraj")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Miasto")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("NrDomu")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("NrLokalu")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Powiat")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Wojewodztwo")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("Adresy");
                });

            modelBuilder.Entity("AddressLibrary.Models.CechaUlicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Skrot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("CechyUlic");
                });

            modelBuilder.Entity("AddressLibrary.Models.Gmina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int>("PowiatId")
                        .HasColumnType("int");

                    b.Property<int>("RodzajGminyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PowiatId");

                    b.HasIndex("RodzajGminyId");

                    b.ToTable("Gminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.KodPocztowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int>("MiastoId")
                        .HasColumnType("int");

                    b.Property<string>("Numery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int>("UlicaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiastoId");

                    b.HasIndex("UlicaId");

                    b.ToTable("KodyPocztowe");
                });

            modelBuilder.Entity("AddressLibrary.Models.Miasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GminaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int>("RodzajMiastaId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("GminaId");

                    b.HasIndex("RodzajMiastaId");

                    b.ToTable("Miasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Pna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dzielnica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Numery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("Pna");
                });

            modelBuilder.Entity("AddressLibrary.Models.Powiat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int>("WojewodztwoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WojewodztwoId");

                    b.ToTable("Powiaty");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajGminy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("RodzajeGmin");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajMiasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("RodzajeMiast");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytSimc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Mz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("RodzajGminy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("RodzajMiasta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("SymbolPodstawowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("TerytSimc");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytTerc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("NazwaDodatkowa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("RodzajGminy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("TerytTerc");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytUlic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("RodzajGminy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("SymbolUlicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("TerytUlic");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytUlicPoprawka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cecha")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Imie2")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwisko2")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Postfiks")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Prefiks")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Pseudonim")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("TerytId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Tytul")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_TerytUlicPoprawki_Id");

                    b.HasIndex("Nazwisko")
                        .HasDatabaseName("IX_TerytUlicPoprawki_Nazwisko");

                    b.ToTable("TerytUlicPoprawki");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytWmRodz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("RodzajMiasta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TerytWmRodz");
                });

            modelBuilder.Entity("AddressLibrary.Models.TypUlicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Imie2")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwisko2")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Postfiks")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Prefiks")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Pseudonim")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int>("TytulStopienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TytulStopienId")
                        .HasDatabaseName("IX_TypyUlic_TytulStopienId");

                    b.ToTable("TypyUlic");
                });

            modelBuilder.Entity("AddressLibrary.Models.TytulStopien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dopelniacz")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Skrot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("TytulyStopnie");
                });

            modelBuilder.Entity("AddressLibrary.Models.Ulica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cecha")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Dzielnica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int>("MiastoId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int?>("TypUlicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiastoId");

                    b.HasIndex("TypUlicyId");

                    b.ToTable("Ulice");
                });

            modelBuilder.Entity("AddressLibrary.Models.UrzadSkarbowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Kod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Miasto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("NrDomu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Ulica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<int?>("UlicaId")
                        .HasColumnType("int");

                    b.Property<string>("Www")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("UlicaId");

                    b.ToTable("UrzedySkarbowe");
                });

            modelBuilder.Entity("AddressLibrary.Models.Wojewodztwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .UseCollation("Polish_CS_AS");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Polish_CS_AS");

                    b.HasKey("Id");

                    b.ToTable("Wojewodztwa");
                });

            modelBuilder.Entity("AddressLibrary.Models.Gmina", b =>
                {
                    b.HasOne("AddressLibrary.Models.Powiat", "Powiat")
                        .WithMany("Gminy")
                        .HasForeignKey("PowiatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.RodzajGminy", "RodzajGminy")
                        .WithMany("Gminy")
                        .HasForeignKey("RodzajGminyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Powiat");

                    b.Navigation("RodzajGminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.KodPocztowy", b =>
                {
                    b.HasOne("AddressLibrary.Models.Miasto", "Miasto")
                        .WithMany("KodyPocztowe")
                        .HasForeignKey("MiastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.Ulica", "Ulica")
                        .WithMany("KodyPocztowe")
                        .HasForeignKey("UlicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Miasto");

                    b.Navigation("Ulica");
                });

            modelBuilder.Entity("AddressLibrary.Models.Miasto", b =>
                {
                    b.HasOne("AddressLibrary.Models.Gmina", "Gmina")
                        .WithMany("Miasta")
                        .HasForeignKey("GminaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.RodzajMiasta", "RodzajMiasta")
                        .WithMany("Miasta")
                        .HasForeignKey("RodzajMiastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gmina");

                    b.Navigation("RodzajMiasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Powiat", b =>
                {
                    b.HasOne("AddressLibrary.Models.Wojewodztwo", "Wojewodztwo")
                        .WithMany("Powiaty")
                        .HasForeignKey("WojewodztwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wojewodztwo");
                });

            modelBuilder.Entity("AddressLibrary.Models.TypUlicy", b =>
                {
                    b.HasOne("AddressLibrary.Models.TytulStopien", "TytulStopien")
                        .WithMany()
                        .HasForeignKey("TytulStopienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TytulStopien");
                });

            modelBuilder.Entity("AddressLibrary.Models.Ulica", b =>
                {
                    b.HasOne("AddressLibrary.Models.Miasto", "Miasto")
                        .WithMany("Ulice")
                        .HasForeignKey("MiastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.TypUlicy", "TypUlicy")
                        .WithMany()
                        .HasForeignKey("TypUlicyId");

                    b.Navigation("Miasto");

                    b.Navigation("TypUlicy");
                });

            modelBuilder.Entity("AddressLibrary.Models.UrzadSkarbowy", b =>
                {
                    b.HasOne("AddressLibrary.Models.Ulica", "UlicaNavigation")
                        .WithMany()
                        .HasForeignKey("UlicaId");

                    b.Navigation("UlicaNavigation");
                });

            modelBuilder.Entity("AddressLibrary.Models.Gmina", b =>
                {
                    b.Navigation("Miasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Miasto", b =>
                {
                    b.Navigation("KodyPocztowe");

                    b.Navigation("Ulice");
                });

            modelBuilder.Entity("AddressLibrary.Models.Powiat", b =>
                {
                    b.Navigation("Gminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajGminy", b =>
                {
                    b.Navigation("Gminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajMiasta", b =>
                {
                    b.Navigation("Miasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Ulica", b =>
                {
                    b.Navigation("KodyPocztowe");
                });

            modelBuilder.Entity("AddressLibrary.Models.Wojewodztwo", b =>
                {
                    b.Navigation("Powiaty");
                });
#pragma warning restore 612, 618
        }
    }
}
