// <auto-generated />
using System;
using AddressLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressLibrary.Migrations
{
    [DbContext(typeof(AddressDbContext))]
    [Migration("20260316065115_ZwiekszenieDlugosciPrefiks")]
    partial class ZwiekszenieDlugosciPrefiks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressLibrary.Models.Adres", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gmina")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kod")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Komentarz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Miasto")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NrDomu")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NrLokalu")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Powiat")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Wojewodztwo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod");

                    b.HasIndex("Miasto", "Kod");

                    b.ToTable("Adresy", (string)null);
                });

            modelBuilder.Entity("AddressLibrary.Models.Gmina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PowiatId")
                        .HasColumnType("int");

                    b.Property<int>("RodzajGminyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nazwa");

                    b.HasIndex("RodzajGminyId");

                    b.HasIndex("PowiatId", "Kod", "RodzajGminyId")
                        .IsUnique()
                        .HasDatabaseName("IX_Gminy_PowiatId_Kod_RodzajGminyId");

                    b.ToTable("Gminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.KodPocztowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("MiastoId")
                        .HasColumnType("int");

                    b.Property<string>("Numery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlicaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kod");

                    b.HasIndex("MiastoId");

                    b.HasIndex("UlicaId");

                    b.ToTable("KodyPocztowe");
                });

            modelBuilder.Entity("AddressLibrary.Models.Miasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GminaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RodzajMiastaId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("GminaId");

                    b.HasIndex("Nazwa");

                    b.HasIndex("RodzajMiastaId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Miasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Pna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dzielnica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pna");
                });

            modelBuilder.Entity("AddressLibrary.Models.Powiat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WojewodztwoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nazwa");

                    b.HasIndex("WojewodztwoId", "Kod")
                        .IsUnique()
                        .HasDatabaseName("IX_Powiaty_WojewodztwoId_Kod");

                    b.ToTable("Powiaty");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajGminy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("RodzajeGmin");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajMiasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("RodzajeMiast");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytSimc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajGminy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajMiasta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolPodstawowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerytSimc");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytTerc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaDodatkowa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajGminy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerytTerc");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytUlic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cecha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajGminy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolUlicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wojewodztwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerytUlic");
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytUlicPoprawka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Pierwsze imię patrona ulicy");

                    b.Property<string>("Imie2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Drugie imię patrona ulicy");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Pierwsze nazwisko patrona ulicy");

                    b.Property<string>("Nazwisko2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Drugie nazwisko patrona ulicy");

                    b.Property<string>("Original")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Oryginalna pełna nazwa ulicy: Cecha + Nazwa2 + Nazwa1");

                    b.Property<string>("Postfiks")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Postfiks/przydomek (np. Zapory, Zośki)");

                    b.Property<string>("Prefiks")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Prefiks nazwy ulicy (np. płk., gen., ks., im., imienia)");

                    b.Property<string>("Tytul")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tytuł osoby (np. dr., prof., płk.)");

                    b.HasKey("Id");

                    b.HasIndex("Nazwisko")
                        .HasDatabaseName("IX_TerytUlicPoprawki_Nazwisko");

                    b.HasIndex("Original")
                        .HasDatabaseName("IX_TerytUlicPoprawki_Original");

                    b.ToTable("TerytUlicPoprawki", (string)null);
                });

            modelBuilder.Entity("AddressLibrary.Models.TerytWmRodz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RozdzajMiasta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StanNa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TerytWmRodz");
                });

            modelBuilder.Entity("AddressLibrary.Models.TypUlicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Pierwsze imię patrona ulicy");

                    b.Property<string>("Imie2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Drugie imię patrona ulicy (np. Kamil w Krzysztofa Kamila Baczyńskiego)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Pierwsze nazwisko patrona ulicy");

                    b.Property<string>("Nazwisko2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Drugie nazwisko patrona ulicy (np. Reymonta w Władysława Stanisława Reymonta)");

                    b.Property<string>("Postfiks")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Postfiks/przydomek (np. Zapory w Hieronima Dekutowskiego Zapory, Zośki w Tadeusza Zawadzkiego Zośki)");

                    b.Property<string>("Prefiks")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Prefiks nazwy ulicy (np. im., Leśny, Miejski)");

                    b.Property<string>("Tytul")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Tytuł osoby (np. dr., prof., płk.)");

                    b.HasKey("Id");

                    b.HasIndex("Nazwisko")
                        .HasDatabaseName("IX_TypyUlic_Nazwisko");

                    b.HasIndex("Imie", "Nazwisko")
                        .HasDatabaseName("IX_TypyUlic_Imie_Nazwisko");

                    b.ToTable("TypyUlic", (string)null);
                });

            modelBuilder.Entity("AddressLibrary.Models.Ulica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cecha")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Dzielnica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MiastoId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nazwa2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("TypUlicyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiastoId");

                    b.HasIndex("Nazwa1");

                    b.HasIndex("TypUlicyId");

                    b.HasIndex("Symbol", "MiastoId", "Dzielnica")
                        .IsUnique()
                        .HasFilter("[Dzielnica] IS NOT NULL");

                    b.ToTable("Ulice");
                });

            modelBuilder.Entity("AddressLibrary.Models.UrzadSkarbowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Miasto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NrDomu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ulica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UlicaId")
                        .HasColumnType("int");

                    b.Property<string>("Www")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Kod");

                    b.HasIndex("Miasto");

                    b.HasIndex("Nazwa");

                    b.HasIndex("UlicaId");

                    b.HasIndex("Miasto", "Ulica");

                    b.ToTable("UrzedySkarbowe", (string)null);
                });

            modelBuilder.Entity("AddressLibrary.Models.Wojewodztwo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("Nazwa");

                    b.ToTable("Wojewodztwa");
                });

            modelBuilder.Entity("AddressLibrary.Models.Gmina", b =>
                {
                    b.HasOne("AddressLibrary.Models.Powiat", "Powiat")
                        .WithMany("Gminy")
                        .HasForeignKey("PowiatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.RodzajGminy", "RodzajGminy")
                        .WithMany("Gminy")
                        .HasForeignKey("RodzajGminyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Powiat");

                    b.Navigation("RodzajGminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.KodPocztowy", b =>
                {
                    b.HasOne("AddressLibrary.Models.Miasto", "Miasto")
                        .WithMany("KodyPocztowe")
                        .HasForeignKey("MiastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.Ulica", "Ulica")
                        .WithMany("KodyPocztowe")
                        .HasForeignKey("UlicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Miasto");

                    b.Navigation("Ulica");
                });

            modelBuilder.Entity("AddressLibrary.Models.Miasto", b =>
                {
                    b.HasOne("AddressLibrary.Models.Gmina", "Gmina")
                        .WithMany("Miasta")
                        .HasForeignKey("GminaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.RodzajMiasta", "RodzajMiasta")
                        .WithMany("Miasta")
                        .HasForeignKey("RodzajMiastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gmina");

                    b.Navigation("RodzajMiasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Powiat", b =>
                {
                    b.HasOne("AddressLibrary.Models.Wojewodztwo", "Wojewodztwo")
                        .WithMany("Powiaty")
                        .HasForeignKey("WojewodztwoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wojewodztwo");
                });

            modelBuilder.Entity("AddressLibrary.Models.Ulica", b =>
                {
                    b.HasOne("AddressLibrary.Models.Miasto", "Miasto")
                        .WithMany("Ulice")
                        .HasForeignKey("MiastoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AddressLibrary.Models.TypUlicy", "TypUlicy")
                        .WithMany()
                        .HasForeignKey("TypUlicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Miasto");

                    b.Navigation("TypUlicy");
                });

            modelBuilder.Entity("AddressLibrary.Models.UrzadSkarbowy", b =>
                {
                    b.HasOne("AddressLibrary.Models.Ulica", "UlicaNavigation")
                        .WithMany()
                        .HasForeignKey("UlicaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UlicaNavigation");
                });

            modelBuilder.Entity("AddressLibrary.Models.Gmina", b =>
                {
                    b.Navigation("Miasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Miasto", b =>
                {
                    b.Navigation("KodyPocztowe");

                    b.Navigation("Ulice");
                });

            modelBuilder.Entity("AddressLibrary.Models.Powiat", b =>
                {
                    b.Navigation("Gminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajGminy", b =>
                {
                    b.Navigation("Gminy");
                });

            modelBuilder.Entity("AddressLibrary.Models.RodzajMiasta", b =>
                {
                    b.Navigation("Miasta");
                });

            modelBuilder.Entity("AddressLibrary.Models.Ulica", b =>
                {
                    b.Navigation("KodyPocztowe");
                });

            modelBuilder.Entity("AddressLibrary.Models.Wojewodztwo", b =>
                {
                    b.Navigation("Powiaty");
                });
#pragma warning restore 612, 618
        }
    }
}
